### ISSUE TITLE
"No module named git" en Windows

### ISSUE THREAD

**Issue by MarianoGomezBidondo** [paxapos/fiscalberry#103]
Luego de haber instalado fiscalberry en WLS (Ubuntu corriendo sobre windows), quise probarlo en DOS Windows. Seguí los pasos de la instalación windows (solamente las dependencias) y me dio ese error 
"No module named git"
Lo pude solucionar con

`pip install gitpython`

Luego de eso funciono sin inconvenientes. Lo dejo registrado acá por si le pasa a alguien en un futuro.
Saludos!

**Comment by alevilar** [comment]
gracias mariano!, agregamos a la rama master este plugin dentro de requirements para que ya les funcione a todos.
