### ISSUE TITLE
No se paso un comando valido

### ISSUE THREAD

**Issue by matiaslp28** [paxapos/fiscalberry#106]
Como estan? Estaba probando, tengo todo levantado ya (estaria bien que pasen un pip freeze porque da varios errores al instalar los requirements, se ve que hubo varias actualizaciones de paquetes).
El problema es que al probar desde la web, recibo un "No se paso un comando valido" al querer imprimir un cierre o un ticket.
Mirando el codigo, es logico que tire ese error pareciera que no esta implementado. Puede ser?

**Comment by gonzaabel** [comment]
Hola Matias, con que comandos te muestra ese error?
Copianos el JSON que intentas mandar así podemos ver si hay algún error en el.

Saludos!
