### ISSUE TITLE
Documentacion: Listado de comandos

### ISSUE THREAD

**Issue by drakorg** [paxapos/fiscalberry#107]
Hola, queria saber si habia disponible una lista de comandos tipo printTicket etc. Vi un par en los ejemplos pero seguramente la lista completa de comandos sea mas larga. Estoy revisando los fuentes pero tal vez ya esta documentado y solo no lo estoy encontrando. 
Gracias,
Saludos

**Comment by gonzaabel** [comment]
Hola @drakorg, en la [wiki](https://github.com/paxapos/fiscalberry/wiki) podrás encontrar en el listado de páginas a la derecha, los comandos listados con JSONs de ejemplo para el manejo general, de impresoras de comandas y las fiscales.

Saludos!

**Comment by drakorg** [comment]
Genial, no lo habia visto, gracias!
Saludos
