### ISSUE TITLE
Consulta Devolucion

### ISSUE THREAD

**Issue by jpgdixon** [paxapos/fiscalberry#111]
Hola, les hago una consulta con respecto a la tmt900fa
como se maneja  la devolucion de items?, me refiero al cambio

**Comment by alevilar** [comment]
me parece es eso es mas una consulta a nivel contable u operativo del
negocio. Por ejemplo, se podria realizar haciendo una NOTA DE CREDITO.

SI es dentro del mismo ticket, es decir cargas 2 cocas y queres quitar 1,
podrias poner  un item en negativo?

eso escapa al uso del driver de fiscalberry. Creo. Quizas no lo entendi
bien.

saludos!
