### ISSUE TITLE
Hasar 615 campo direccion

### ISSUE THREAD

**Issue by catrielr** [paxapos/fiscalberry#22]
Despues del [https://github.com/paxapos/fiscalberry/issues/19](url)
Ahora pasa algo mal  con el modelo 615 el error esta en la direccion.
Con la 715v1 y 715v2 sale OK

Paso salida de consola.
ComandoException: Error de la impresora fiscal: Campo de datos no válido.
Comando enviado: SEND|0x62|F|['Loco Computacion SRL', '30709211101', 'C', 'C', u'Av. Mitre 1111']

Sale con esa "u"

**Comment by alevilar** [comment]
hola @catrielr verificá porfa que te funcione. Creo ya haber arreglado este bug. Si no funciona reabrí la issue!!

saludos
