### ISSUE TITLE
Epson no imprime items de las facturas

### ISSUE THREAD

**Issue by catrielr** [paxapos/fiscalberry#23]
Despues del [https://github.com/paxapos/fiscalberry/pull/20](url) 
No imprime los items y deja el comprobante abierto.

Solo Epson, en Hasar funciona bien

Veo que da el problema en: [https://github.com/paxapos/fiscalberry/blob/master/Comandos/EpsonComandos.py#L233](url)

Pero hasta aca llego mi conocimiento.

Saludos
Catriel

**Comment by alevilar** [comment]
@catrielr probalo y si no funca reabrite la issue. Ya deberia andar. pero no tengo Epson para probar y en Linux tampoco tengo el emulador :penguin:

**Comment by catrielr** [comment]
Imprime ok los detalles
