### ISSUE TITLE
Permiso denegado a /dev/ttyUSB0

### ISSUE THREAD

**Issue by AlexisCaffa** [paxapos/fiscalberry#28]
`IOError: [Errno 13] Permission denied: '/dev/ttyUSB0'`  

Ejecuté `sudo chmod 666 /dev/ttyUSB0`, aparentemente anda. ¿Es seguro?

[Posible solución](https://stackoverflow.com/questions/27858041/oserror-errno-13-permission-denied-dev-ttyacm0-using-pyserial-from-pyth)

**Comment by gonzaabel** [comment]
Hola, ese error de permiso no debería aparecerte si ejecutas el servidor con permisos de sudo.
De ultima también podrías ir a la carpeta dev y ver que grupo de usuario tiene permiso al dispositivo y meter a tu usuario en el para tener permisos.
Saludos!

**Comment by AlexisCaffa** [comment]
Perfecto
