### ISSUE TITLE
Se cuelga el servicio ante situaciones de error

### ISSUE THREAD

**Issue by MarianoGomezBidondo** [paxapos/fiscalberry#44]
Cuando por algun motivo hay error (la impresor no responde, se desconecto, el comando es incorrecto, o lo que fuera) tira el error en el servidor y el servicio deja de responder; para que continue hay que cerrarlo y volver a ejecutar el server.py.
Hay posibilidad de que retorne el error y luego continue esperando comandos?

Saludos!

**Comment by alevilar** [comment]
En realidad ese es el comportamiento. Retornar los errores pero seguir
funcionando.
Seguramente estés teniendo un error que no hayamos detectado. Podrías
copiarnos todo lo que te aparece en consola? Saludos

**Comment by alevilar** [comment]
@MarianoGomezBidondo podrias enviarnos el error asi te ayudamos con esto!, saludos
