### ISSUE TITLE
Evento Fiscalberry

### ISSUE THREAD

**Issue by alanemiliano** [paxapos/fiscalberry#50]
![eventomeetup](https://user-images.githubusercontent.com/31542892/36321655-445b14e4-1329-11e8-8de7-28ac38621ba8.jpg)

Hola, soy integrante del equipo de desarrollo de PaxaPos y quiero invitarlos a participar en una charla de programadores sobre el proyecto Fiscalberry.
Sera este jueves 22 de febrero a las 19:00 PM de Argentina (-03GMT) mediante la plataforma Google Hangouts (para poder participar en la charla no es necesario tener altos conocimientos de programación).
Los temas que se van tratar son relacionados al proyecto Open Source de Fiscalberry los cuales serán:	

1. Presentarnos
2. Compartir conocimientos entre todos y la experiencia de cada uno.
3. Organizar el proyecto y priorizar tareas de desarrollo entre todos
4. Inclusión de todas las personas que quieran participar en este proyecto
5. Mini-tutorial sobre como comenzar a desarrollar un driver o comando para fiscalberry. Conceptos básicos de la arquitectura.

Si quieres asistir o te interesa la propuesta podrás marcar la opción deseada en nuestro evento en Facebook: [https://www.facebook.com/events/1580220802025689/](https://www.facebook.com/events/1580220802025689/)
Atte. 
Equipo de desarrollo PaxaPos.

**Comment by gonzaabel** [comment]
¿Cómo sera el meetup de hoy?

Por medio de hangouts de google conversaremos por chat, audio y video. Pero, para quienes no se animen a la camarita ni al chat, iniciaremos streaming en vivo por youtube en el siguiente link: https://youtu.be/nfNeVmUAFVU
