### ISSUE TITLE
Crear Driver para Emulador Hasar 2 Gen

### ISSUE THREAD

**Issue by alevilar** [paxapos/fiscalberry#53]
Conectar con el emulador de Hasar cuya doc y PDF´s de comandos estan subidos a la wiki y se pueden descargar aca:

http://grupohasar.com/wp-content/uploads/2017/09/IFH-2G-Distribucion-170725.zip

**Comment by gonzaabel** [comment]
Ya esta hecho, funciona con el JsonDriver y funciona solo en Windows ya que el emulador es dependiente del http2package (este nose si estará disponible en Linux, puede que si) y del emulador Hasar que solo esta disponible en Windows (este emulador en el SO del Willie Puertas, requiere instalar aparte el com0com para generar la apertura de un puerto COM virtual). Si algún día Hasar hace un emulador para Linux, veremos que cosas se necesitan para hacerlo funcionar (esperemos que lo hagan, seria un golazo).
