### ISSUE TITLE
Bloqueo con https

### ISSUE THREAD

**Issue by dydsoft** [paxapos/fiscalberry#67]
Hola, ya tengo todo funcionando, de forma local no tengo ningún problema. Pero al pasar todo el sistema a mi servidor el cual funciona bajo https, el navegador bloquea el uso del ws://, la solución para evitar ese bloqueo fue cambiarla a wss://, pero el problema ahora es que no se establece una conexión con el servidor de fiscalberry.
Alguna recomendación ya que no tengo mucha experiencia en python.

**Comment by alevilar** [comment]
tambien podrias usar un certificado y una KEY, agregarla a la configuracion
y se instancia una WSS

[SERVIDOR]
ssl_crt_path = /mycert.crt
ssl_key_path = /mykey.key


el problema con eso es que tenes que instalar el certificado en cada
browser, salvo que el servidor de websockets lo tengas en un servidor cn IP
publica a internet(cosa que dudo)

igual no la tengo super clara con eso... pero "mas o menos" seria asi.... y
tendrias conexion segura al websocket





2018-04-13 20:21 GMT-03:00 dydsoft <notifications@github.com>:
