### ISSUE TITLE
Error fiscalberry en Windows [Error parseando el JSON__init__() got an unexpected keyword argument 'host']

### ISSUE THREAD

**Issue by renzohcoronel** [paxapos/fiscalberry#82]
Hola a todos. Dado que no tengo la posibildad de conseguir una impresora fiscal para probar, decidí levantar el emulador de impresoras fiscales (http://www.impresoras-fiscales.com/emulador.htm) con la intencion de probrar fiscalberry. En linux no pude hacer funcionar correctamente el emulador con wine, por esto instale en windows ambas cosas.

El emulador lo instale sin ningun problema.
![images001](https://user-images.githubusercontent.com/16545544/51054303-35f7a300-15bb-11e9-86d4-a8761ab58e3a.jpeg)

En la instalacion de fiscalberry tuve que instalar manualmente algunas dependencias pero funciono todo correctamente. La impresora mas parecida a la que contamos en la empresa  es la SMH330 en el emulador.

![images002](https://user-images.githubusercontent.com/16545544/51054433-9ab2fd80-15bb-11e9-9f10-c6863bac75a4.jpeg)

Ahora al momento de enviar los json desde la aplicacion web, fiscalberry me arroja el siguiente error.

![images003](https://user-images.githubusercontent.com/16545544/51054727-7277ce80-15bc-11e9-8452-38b52022a053.jpeg)

Busque un poco en el codigo, pero no soy muy ducho con Python. 

¿Alguna sugerencia de a que se puede deber este error?

Saludos.

**Comment by gonzaabel** [comment]
Hola Renzo, lo que esta sucediendo seguramente se deba a que en el config.ini tengas una configuración para la impresora fiscal similar a esta:
```INI
[IMPRESORA_FISCAL]
marca = Hasar
modelo = sh330
driver = Hasar
path = COM2
host = ''
```
Tendrías que remover el atributo `host` para que funcione correctamente.
Prueba y nos avisas :)

**Comment by renzohcoronel** [comment]
@gonzaabel gracias por tu respuesta. Tenias razon. Disculpen la pregunta quizas tonta. No soy muy ducho con python y crei que podia ser algun problema de alguna libreria. 

Para hacer una consulta nueva es necesario que lo habra como un issue nuevo o puedo consultar por aca. La realizo cualquier cosa la modifico y lo abro como un nuevo issue.

En la empresa somos agentes de retencion y no probe aun, pero en la wiki no encuentro nada para poder enviar dos tipos de impuestos (Ingresos brutos y Tasa de Seguridad e Higiene) 

Saludos.

**Comment by gonzaabel** [comment]
> @renzohcoronel says: 
@gonzaabel gracias por tu respuesta. Tenias razon. Disculpen la pregunta quizas tonta. No soy muy ducho con python y crei que podia ser algun problema de alguna libreria.

¡No pasa nada! Estamos para ayudar voluntariamente y compartir conocimientos, ideas, problemas y soluciones para hacer de Fiscalberry un proyecto mejor y que nos sirva a todos. :smile: 
Este pequeño problema en particular me parece que se genera al modificar el tipo de conexión en el panel de configuración que esta en la página HTML. Por alguna razón en el config.ini cuando se escribe la nueva configuración que llega desde ese panel, no esta borrando el campo anterior (en este caso, al cambiar de host a path, no se estaría borrando el campo host del config.ini. Le echare un vistazo en cuanto pueda).

> Para hacer una consulta nueva es necesario que lo habra como un issue nuevo o puedo consultar por aca. La realizo cualquier cosa la modifico y lo abro como un nuevo issue.

Puedes consultar directamente en esta issue aunque este cerrada. Para reportar un nuevo problema si sera necesario que abras una nueva.

> En la empresa somos agentes de retencion y no probe aun, pero en la wiki no encuentro nada para poder enviar dos tipos de impuestos (Ingresos brutos y Tasa de Seguridad e Higiene)

En el caso de Ingresos Brutos, la factura o ticket al estar destinado a una empresa (Factura A) te lo debería discriminar el controlador fiscal porque es un porcentaje de los totales sumados de los items facturados al igual que con el IVA (si no me equivoco). 
Después con la tasa desconozco, ya que hay una diferencia entre tasas e impuestos (tasa es un monto fijo e impuesto es un porcentaje, pero me dijo un contador que hicieron un arreglo con un juez hace unos años para declarar esa tasa que mencionas como un impuesto que sería de un 1%, aunque es una tasa municipal y por ende es ilegal que los municipios puedan cobrar impuestos, solo pueden aplicar tasas. Pero esta clase de "arreglos" pasan en Argentina...). 
Si es un monto fijo, puede que te sirva enviar dicha tasa como un item. Aunque se le estaría aplicando un IVA sobre eso así que dudo mucho que sea lo que estés buscando.
Puede que lo que necesites sean uno o más comandos que no tengamos contemplados. Estaría genial implementarlos. Para ello habrá que leer la documentación de Hasar para los mismos.
Acabo de mirar y encontre un commit en un fork el cual trata de poder añadir percepciones: https://github.com/ssaid/fiscalberry/commit/622eceaa8694e64cd941b0490c6ab50ade3f452b
A lo mejor sea eso lo que necesitas para la tasa y de todas formas planeamos mergearlo pronto.

Saludos.

**Comment by renzohcoronel** [comment]
@gonzaabel buenisimo.. TISH y IIBB son percepciones. Voy a mirarlo
Saludos.

**Comment by gonzaabel** [comment]
Hola @renzohcoronel perdón la demora. Ya está el comando de percepciones disponible para Hasar en Fiscalberry. Bájate el ultimo commit y pruebalo 👍
