### ISSUE TITLE
Error "ImportError: No module named ordered_dict" al iniciar fiscalberry por primera vez

### ISSUE THREAD

**Issue by Carlospiad** [paxapos/fiscalberry#88]
Al intentar iniciar fiscalberry por primera vez con :
`sudo python server.py
`
obtengo el siguiente error:
`ImportError: No module named ordered_dict
`
Investigando, al parecer tenía la versión urllib3-1.24.2, la cual da error.

La solución manual fue:
1. Desinstalar urllib3:  `sudo pip uninstall urllib3`
2. Instalarlo con la versión fija `sudo pip install urllib3==1.22`

**Comment by Carlospiad** [comment]
Recomiendo actualizar requirements.txt para cambiar de `urllib3>=1.22` a `urllib3==1.22`

**Comment by gonzaabel** [comment]
Bien, gracias por tu contribución :smile: :+1:
