### ISSUE TITLE
Documentación SDK

### ISSUE THREAD

**Issue by pasmaan** [paxapos/fiscalberry#90]
Buenos días,

Quisiera saber si se provee de un SDK para este tipo de impresoras fiscales o si existe el mismo, ya que estoy intentando realizar un desarrollo en Android y me vendría bien alguna ayuda. Estuve buscando en internet pero la verdad es que no hay mucho.

Saludos.

**Comment by alevilar** [comment]
para android no te va a servir. Fiscalberry es para ser utilizado como
servidor de websockets con tornado (python). Al menos nosotros aun no
logramos hacerlo funcionar en andriod.

**Comment by joseluisbossio** [comment]
Nosotros tampoco (aún)

**Comment by pasmaan** [comment]
Uff durisimo, además la mayoria del mercado tiene impresores de primera generación. Voy a investigar más, cualquier cosa aviso. 
Saludos y gracias.

**Comment by mtotaro** [comment]
Buenas tardes estimados,

Para a los que les interese, dejo mi humilde aporte:

https://github.com/grupohasar/HasarFiscalDriver

Enjoy 

Saludos.
